---
 - name: install and start docker
   hosts: all
   user: root
   tasks:
    - name: install docker
      yum: pkg=docker state=latest
   
    - name: create docker image 
      shell: docker run -d --name centos1 centos
