---
 - name: install and start docker
   hosts: all
   user: root
   tasks:
    - name: install docker
      yum: pkg=docker state=latest

    - name: start docker
      service: name=docker state=started
