---
 - hosts: all
   become: true
   tasks: 
    
    - name: to start the docker  
      shell: systemctl enable docker && systemctl start docker
    - name: to restart docker
      shell: systemctl start docker
    - name: to remove old docker container
      shell: docker rm -f rj_demo
    - name: create docker image 
      shell: docker run -d --name rj_demo -p 8090:8080 tomcat
    
