---
 - hosts: all
   become: true
   tasks: 
    - name: stop previous version docker
      shell: docker stop rj_demo
    - name: remove stopped container
      shell: docker rm -f rj_demo
    - name: remove docker images
      shell: docker image rm -f rj_demo
    - name: create docker image 
      shell: docker run -d --name rj_demo -p 8090:8080 tomcat