---
 - hosts: httpd
   become: true
   tasks: 
    - name: to install docker 
      shell: yum install docker -y
    - name: to start the docker  
      shell: systemctl enable docker && systemctl start docker
    - name: to restart docker
      shell: systemctl restart docker
    - name: create docker image 
      shell: docker run -d --name rj_demo -p 8090:8080 tomcat
    
